# Base configs
baseurl: "https://photography.jetsquared.com"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Photography by JET Squared"
subtitle: "Seeing the world through a new lens"
author: "James Taylor II"
header:
 title: "Photography"
 subtitle: "by JET Squared"
footer:
 name: ""
 bio: "A husband, father, and a follower of the Lord Jesus Christ. I am an engineer at heart and love all things tech. Photography is a newly found interest and I'm loving this new 'view' of the world!"
 github: "I 'forked' this directly from <a href=\"https://github.com/ramswaroop/photography\">ramswaroop</a>.  Currently, all credit for the website and design can be found on his page (don't reinvent the wheel, right?).;)"
web_design: "AJ"
social_urls:
  # facebook: "https://www.facebook.com/ramswaroop"
  # twitter: "https://www.twitter.com/ram__patra"
  # instagram: "https://www.instagram.com/ram_patra"
  # dribbble: "https://dribbble.com/jetsquared"
  # linkedin: "https://in.linkedin.com/in/ram-patra"
  github: "https://www.github.com/jetsquared"
theme: jekyll-theme-merlot
